"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import Navebar from "./_Components/Header/NavebarSection/navebar";
import { useState } from "react";
import { createContext } from "react";

export const ManuContext = createContext(null);

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [manufacturer, setManufacturer] = useState([]);

  return (
    <html lang="en">
      <ManuContext.Provider value={[manufacturer, setManufacturer]}>
        <body className={inter.className}>
          <Navebar />
          {children}
        </body>
      </ManuContext.Provider>
    </html>
  );
}
